version: '3.7'
services:
  ynab:
    build: .
    volumes:
    # Mount the X11 socket so that we can share graphics with the host system
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ~/.Xauthority:/home/docker/.Xauthority
    # Map the YNAB directory on the host. This is where YNAB software is installed
    - ~/YNAB:/home/docker/YNAB
    # Contains saved/synced budgets. Change the source directory to Dropbox, etc
    - ~/YNAB-budgets:/home/docker/Documents
    environment:
    # Pass through the hosts DISPLAY env setting
    - DISPLAY=${DISPLAY_IP}:0
    # Sometimes YNAB wants to render a pop-up/pop-under that kills the
    # process due to a problem with OpenGL (most likely). Setting this
    # may make rendering slower, but it makes it more reliable.
    - LIBGL_ALWAYS_SOFTWARE=1    